#!/usr/bin/env bash
# Generate a tubular .theme file from a base16/base24 scheme file, so ANY of
# the 250+ schemes at https://github.com/tinted-theming/schemes works with
# tubular. Writes the theme to stdout:
#
#   theme-import-base16.sh rose-pine-moon.yaml > ~/.config/tmux/my.theme
#   # then:  set -g @tubular_theme "~/.config/tmux/my.theme"
#   # or drop it into the plugin's themes/ dir to use it by bare name.
#
# Mapping (base16 style-guide semantics -> tubular roles):
#   base00 bg    base01 bg_max (the spec's "status bar" slot)   base02 bg_min
#   base05 fg    base06 fg_active    base07 fg_focus
#   base04 neutral_visible    base03 neutral_hidden
#   base0E (purple) prefix vs base0B (green) copy — the classic max-contrast
#     pair for the modes that share the screen with normal panes
#   base0C (cyan) active border — conventionally the calmest accent
#   base0D (blue) zoom — the cyan look-alike, exiled to the one mode that is
#     only ever seen with its pane filling the screen
#
# This is a deterministic mapping of base16 hue *conventions*; a scheme that
# bends them (e.g. puts orange in base0E) deserves a hand-tune of the
# generated file. The bundled presets in themes/ are hand-tuned for exactly
# that reason.

set -euo pipefail

scheme="${1:?usage: theme-import-base16.sh <scheme.yaml>}"
[ -r "$scheme" ] || { echo "error: cannot read $scheme" >&2; exit 1; }

# Pull baseXX: "hex" out of the YAML without a YAML parser. Handles the
# current tinted-theming layout (palette: block, quoted "#rrggbb") and the
# legacy base16 layout (top-level, unquoted rrggbb).
get() {
  sed -n -E "s/^[[:space:]]*\"?${1}\"?:[[:space:]]*[\"']?#?([0-9a-fA-F]{6})[\"']?.*/\1/p" "$scheme" | head -1
}

for k in 00 01 02 03 04 05 06 07 0B 0C 0D 0E; do
  v=$(get "base$k")
  [ -n "$v" ] || { echo "error: base$k not found in $scheme" >&2; exit 1; }
  printf -v "b$k" '#%s' "$v"
done

name=$(sed -n -E "s/^[[:space:]]*\"?name\"?:[[:space:]]*[\"']?([^\"']+)[\"']?.*/\1/p" "$scheme" | head -1)

cat <<EOF
# tubular theme: ${name:-$(basename "$scheme")}
# Generated by theme-import-base16.sh from $(basename "$scheme").
# Deterministic base16 mapping — hand-tune if this scheme bends the base16
# hue conventions (see the script header for the role assignments).
th_bg="$b00"; th_bg_max="$b01"; th_bg_min="$b02"
th_fg="$b05"; th_fg_active="$b06"; th_fg_focus="$b07"
th_neutral_visible="$b04"; th_neutral_hidden="$b03"
th_zoom="$b0D"; th_copy="$b0B"; th_prefix="$b0E"; th_active="$b0C"
th_border_lines="single"; th_normal_xb="0"; th_active_xb="1"
th_prefix_xb="1"; th_copy_xb="1"
EOF
